DW: false
Soft_T: 2.0
batch_size: 64
config: configs/cifar-100_prompt.yaml
dataroot: data
dataset: CIFAR100
debug_mode: 0
first_split_size: 10
gpuid:
- 0
- 1
kd_alpha: 0.5
learner_name: CODAPrompt
learner_type: prompt
log_dir: outputs_test_0727_t_prompt_s_prompt_projectCODAPrompt_No_Kd_tokens_buthave_kdlast_useKLDivLoss_basetosmall_cifar100_01/cifar-100/10-task/coda-p
lr: 0.001
max_task: -1
memory: 0
model_name: vit_pt_imnet
model_type: zoo
momentum: 0.9
optimizer: Adam
other_split_size: 10
overwrite: 0
prompt_param:
- 100.0
- 8.0
- 0.0
rand_split: true
repeat: 1
s_model: vit_small_patch16_224
schedule:
- 20
schedule_type: cosine
t_model: vit_base_patch16_224
train_aug: true
upper_bound_flag: false
validation: false
weight_decay: 0
workers: 4
