DW: false
Soft_T: 2.0
batch_size: 32
config: configs/imnet-r_prompt.yaml
dataroot: data
dataset: ImageNet_R
debug_mode: 0
first_split_size: 20
gpuid:
- 0
- 1
kd_alpha: 0.5
learner_name: DualPrompt
learner_type: prompt
log_dir: outputs_test_0723_t_prompt_s_prompt_projectCODAlayer_No_Kd_tokens_buthave_kdlast_useKLDivLoss_basetosmall_epoch35_testall_11/ImageNet_R/10-task/dual-prompt
lr: 0.001
max_task: -1
memory: 0
model_name: vit_pt_imnet
model_type: zoo
momentum: 0.9
optimizer: Adam
other_split_size: 20
overwrite: 0
prompt_param:
- 10.0
- 20.0
- 6.0
rand_split: true
repeat: 1
s_model: vit_small_patch16_224
schedule:
- 35
schedule_type: cosine
t_model: vit_base_patch16_224
train_aug: true
upper_bound_flag: false
validation: false
weight_decay: 0
workers: 4
